# ScalpPlaza {#a-more-efficient-ticket-marketplace}

#### Keywords

tickets, exchange, sports, concerts, theatre, entertainment, fun, fun, fun

## A free, yet complacent, marketplace.

Spending the last five years working for a market-making trading firm has deepened my appreciation of the efficiency and simplicity associated with free market economic systems. As fascinating as watching myriad derivatives marketplaces evolve and sophisticate over the years has been, it has been equally frustrating participating in other marketplaces which have shown little sign of innovation. One such example of a stagnant marketplace is that of secondary tickets. A long-time Chicago Cubs season ticket holder, I inevitably find myself trying to sell last-minute tickets to many of their 81 regular season home games as conflicts arise and other matters take priority. I currently have three options to do so:

 1.	Venture up to Wrigley Field and try to sell them the old fashioned way. This involves either trying to be louder and more aggressive than the traditionally brash and slimy crew of ticket-scalpers already stationed there, or getting lowballed and selling the tickets directly to the same people. Regardless, this is a generally undesirable option and easily the most time- and energy-intensive of the three.
2.	List the tickets in the “for sale” section of a classified advertisement website such as Craigslist. These websites, while free to use, are antiquated, largely unregulated, and thus rife with scam artists. Additionally, there is no guarantee a buyer will be found.
3.	List the tickets on an online ticket exchange such as StubHub or SeatGeek. While relatively painless to use, these sites are known for charging exorbitant fees (StubHub, for example, pockets 20% of every transaction) and significantly cut into sale margins. Also, like posting in classifieds, there is no guarantee a buyer will be found. 


## It’s simple: buy low, sell high.

ScalpPlaza’s goal is to provide users with an efficient, two-sided marketplace for any and all live entertainment events. While most incumbent online ticket exchanges only display the prices at which tickets are offered, ScalpPlaza will display both bids and offers. This will allow users to buy or sell tickets in seconds when they’re in a rush or to try “cutting the market” in hopes of getting a better deal when they can afford to be patient. 

ScalpPlaza’s primary differentiating factor, however, is its ability and willingness to act as a middleman by transacting with its users and accumulating ticket positions when the market is illiquid. This will be made possible through the use of a data-driven algorithmic ticket-pricing model. Essentially, ScalpPlaza will utilize historical data, market trends, and machine-learning in order to best predict what a ticket is worth on the open market based on the event’s original ticket price, performer(s), location, venue, date, expected weather, social media #buzz, and any other pertinent factors. The model will eventually use this estimated ticket value and a confidence interval to generate both bid and offer prices for any given ticket. These prices will then drift dynamically based on informational changes, order flow, and ScalpPlaza’s internal ticket inventory.


## Let the machine go to work.

ScalpPlaza’s ultimate goal is to end the age-old “maximize profit or save energy” debate had by those looking to buy or sell secondhand tickets by providing them with a tight, two-sided ticket exchange platform. The largest roadblock I foresee is the current state of what is already a saturated secondhand ticket marketplace, led be the eBay-owned behemoth StubHub. The concept of “shorting” tickets is another potential issue which will have to be investigated, both legally and logistically, before launching. Trying to wedge ScalpPlaza’s foot in the door will be an arduous process but if it can succeed in attracting even a small base of regular users, a steep growth curve should ensue as its machine-learning algorithm goes to work. The more ticket transactions that go through ScalpPlaza, the more data it acquires, the smarter its algorithm becomes, and the tighter the ticket markets its willing to offer become.  The tighter the markets, the better the customer experience. The better the customer experience, the more likely customers are wanting to return for their next ticket transaction, resulting in even more troves of data in ScalpPlaza's database. This beautiful, cyclical process makes everyone a winner. Well, everyone except the other ticket resale sites.


