# ReLux: Pay for community and amenities, not superfluous apartment space {#Rearranged-Luxury}

#### Keywords {-}

luxury, amenities, city living, apartments, microunits, regression analysis, polling, clustering, machine learning 

## Smaller apartments, bigger lifestyles.

The last two centuries have seen a steady increase in the proportion of Americans living in the country’s cities. After hovering around 5% during America’s incipient days as a rural, agricultural nation, this number has recently climbed north of 82%. Given this trend of urbanization, the finite amount of city space available, and population growth in general, it should come as no surprise that the relative cost of living in a city continues to rise. ReLux hopes to help hopeful city-dwellers combat these rising prices without sacrificing everyday luxuries by offering a new kind of apartment living. ReLux believes that people should pay for comfort and community, not for superfluous apartment space. By limiting the size of its residents’ personal quarters, ReLux will be able to provide top-of-the-line amenities and a collaborative, community-driven environment at a reasonable price.

## Regress for progress.

ReLux's target demographic is anyone and everyone who is fed up with the prices or structure of traditional apartment city living. ReLux is for Dave, a transplant from another city who is looking to meet like-minded individuals and make some potential new friends. ReLux is for Susan, the workaholic who needs a nice, quiet place to sleep but does not want to splurge on a 500 square foot apartment. ReLux is for Betty, the entrepreneur who pays rent to sleep in one place and more rent to work in another. ReLux is for Juan, the commuter who is seeking a bit more intimacy and familiarity than he currently gets out of his traditional weekly hotel stays. ReLux aims to locate the cities where the Daves, Susans, Bettys, and Juans are most prevalent; speaking more generally, preliminary reseach will focus on finding cities with recent influxes of singles and millenials, cities with relatively high numbers of entrepreneurs and freelancers, and cities lacking sufficient residential options for those willing to sacrifice size, but not necessarily luxury, for price. This information can then be used in conjunction with further analysis of occupation distribution, cost of living indices, general geographical dispositions, and potential competition in order to determine ReLux's most promising launch options. 

Apartment sizes will vary both within and between locations but the norm will be a space of roughly 60 square feet per person. Conversely, common areas will be spacious, plenty, and multi-functional. One of the keys to ReLux's success will be accommodating and adapting to the constantly changing needs and desires of society. ReLux hopes to gain a thorough understanding of what people in various locations value in their domestic spaces by supplementing traditional polling data with modern data science. Applying regression analysis, clustering, and other machine learning techniques to the troves of publically available housing data (residential layouts, housing prices, renovation details, etc.) should help ReLux better stay abreast of intra-city, inter-city, and nationwide trends. For example, would potential inhabitants in San Francisco's Mission District tend to prefer extra offices or additional space to hang out and socialize? Would those in Manhattan feel similarly or would they instead prefer a larger gym? Lifestyle trends will also be accounted for in ReLux's layout-optimization model; kitchen space, for example, is likely to be a particular area of interest over the next few years given the growing meal kit industry's potential to spark a resurgence in home cooking. While each building's initial layout will be important, equally as vital will be continued research and maintaining an active dialogue with inhabitants in order to properly assess if and when changing societal needs justify investing time and money on a communal area remodel.

## A new niche niche.

While the continued urbanization of America is often hailed as a sign of progress and prosperity, one undeniably adverse side effect is a growing disparity between what city dwellers want in a home and what they are able to afford. ReLux aspires to provide a modern, luxurious, community-driven, and economically-feasible option to those looking to live downtown. The sheer magnitude of what Relux hopes to do, both literally and figuratively, provides a couple of foreseeable barriers to implementation. The first is the significant initial investment required in purchasing any sort of property. Moreover, that investment is subject to sometimes unpredictable fluctuations in housing prices, which can be a tough pill for some risk-adverse investors to swallow. One option which could be exercised to bypass these concerns altogether would be for ReLux to partner with a construction and development company until it can get its feet off the ground. Although doing so would cut into its profit potential, it would turn a potential rival into a teammate, drastically reducing ReLux's downside risk in the process. Pairing with a construction and development company would also allow ReLux to focus the entirety of its resources on locating its most potentially fruitful expansion cities and layout-optimization within those cities. Another possible hindrance could stem from asking people to break with the status quo and welcome a new style of living. Admittedly, ReLux is not for everybody; but in an age where [shared workspaces](https://www.cbinsights.com/research/wework-valuation-analysis/) and [tiny homes](http://www.countryliving.com/home-design/g1887/tiny-house/?) are all the rage, ReLux is confident in its ability to carve out a new lifestyle niche and ultimately leverage a "less is more" approach in fostering and maintaining successful communities. 
